spring:
  application:
    name: easyfix
  datasource:
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    username: ${DB_USER}
    hikari:
      connectionTimeout: 60000
      idleTimeout: 300000
      minimumIdle: 1
    jpa:
      show-sql: false
      properties:
        hibernate:
          show_sql: false
          format_sql: false