CREATE TABLE IF NOT EXISTS easy_fix.user(
  id INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
  name VARCHAR(100) NOT NULL,
  email VARCHAR UNIQUE NOT NULL,
  password VARCHAR NOT NULL,
  role VARCHAR NOT NULL CHECK (role IN ('USER', 'SERVICE_PROVIDER')),
  created_date TIMESTAMP WITH TIME ZONE NULL,
  updated_date TIMESTAMP WITH TIME ZONE NULL,
  CONSTRAINT pk_easy_fix_user PRIMARY KEY
  (
      id
  )
)